name: Build All (Python + uv)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  matrix-build:
    uses: FelipeFuhr/ffreis-workflows-python/.github/workflows/python-build.yml@v1.0.1
    with:
      python-versions: '["3.14", "3.13", "3.11", "3.10"]'
      uv-extras: "dev cli"
      test-dir: "tests/unit_tests"
